services:
  hapi-fhir-jpaserver-start:
    build:
      context: .
      target: default
    container_name: hapi-fhir-jpaserver-start
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://hapi-fhir-postgres:5432/hapi"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "admin"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
      HAPI_FHIR_GENERATION_ENABLED: "true"
      HAPI_FHIR_GENERATION_JAR_PATH: /opt/generation/dolus.jar
      HAPI_FHIR_GENERATION_INPUT_BASE_DIR: /opt/generation/realms
      HAPI_FHIR_GENERATION_WORK_DIR: /opt/generation/work
      HAPI_FHIR_GENERATION_MAVEN_PATH: mvn
    ports:
      - "${HAPI_HTTP_PORT:-8080}:8080"
    volumes:
      - ../dolus/target/dolus.jar:/opt/generation/dolus.jar:ro
      - ../dolus/input:/opt/generation/realms:ro
      - ../dolus/output:/opt/generation/work
    depends_on:
      hapi-fhir-postgres:
        condition: service_healthy
  hapi-fhir-postgres:
    image: postgres:16-alpine
    container_name: hapi-fhir-postgres
    restart: always
    environment:
      POSTGRES_DB: "hapi"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U admin -d hapi' || exit 1"]
      interval: 10s
      timeout: 5s
      start_period: 5s
      retries: 5
    volumes:
      - hapi-fhir-postgres:/var/lib/postgresql/data

volumes:
  hapi-fhir-postgres:
